### PR TITLE
Add `dbt-project` type mapping (from fork)

### PR DESCRIPTION
**Pull request by pranasziaukas**
This change introduces a new `dbt-project` repository type mapping, designed specifically for dbt (data build tool) projects, such as https://github.com/balena-io/analytics-dbt-models

All dbt projects require a standard `dbt_project.yml` configuration file at a minimum, which is used in this script.

For reference, see https://docs.getdbt.com/docs/build/projects

### CODE REVIEW

**Comment by pranasziaukas** [comment]
Inspired heavily by https://github.com/product-os/balena-versionist/pull/95

**Comment by pranasziaukas** [comment]
cc @Page- (since you approved the previous PR), @gantonayde, @AlidaOdendaal

**Comment by gantonayde** [comment]
As Pranas mentioned, this change is analogous to the python poetry inclusion to balena-versionist types and is needed by the analytics team to kick off the dbt project.

**Comment by pranasziaukas** [comment]
Closing in favor of https://github.com/product-os/balena-versionist/pull/115 since engineers now have write access to the repository

**Pull request closed without merging**
