### PR TITLE
Pass title info to versionist

### PR DESCRIPTION
**Pull request by stathismor**
Title info can be passed along (--title, -t).

Change-type: minor
Depends on: https://github.com/product-os/versionist/pull/208

### CODE REVIEW

**Comment by Hades32** [comment]
LGTM, but converted to draft, as PR it depends on hasn't landed yet

**Comment by stathismor** [comment]
@balena-ci rebase

**Comment by stathismor** [comment]
@balena-ci rebase

**Comment by stathismor** [comment]
@balena-ci I self-certify!

**Pull request merged**
