### PR TITLE
Use `spawnAsync` instead of `execAsync` to avoid the shell entirely

### PR DESCRIPTION
**Pull request by Ereski**
Change-type: patch
Signed-off-by: Carol Schulze <carol@balena.io>

### CODE REVIEW

**Comment by kb2ma** [comment]
@ereski, unfortunately I don't have the background to provide a useful review on these changes, so I removed myself from the list of reviewers.

**Comment by Ereski** [comment]
ah, sorry, GH recommended you for some reason @kb2ma

**Comment by Ereski** [comment]
@alexgg I think you're the only one that is able to review this?

**Comment by Ereski** [comment]
background on this change: https://www.flowdock.com/app/rulemotion/r-beginners/threads/Sx1kPRPTL9Bw3aP7PRTE6sTM9ap

**Pull request closed without merging**
